### ISSUE TITLE
Cannot Open the Connections

### ISSUE THREAD

**Issue by rosy-li** [quantixed/TrackMateR#9] opened 2023-04-05 14:50 UTC
Hi, 
I am having a connection issue in my console. Whenever I run the "compareDatasets" or run a couple of samples in the same session, it always reports "Error in file(con, "w"): cannot open the connection". So I strongly encourage you add the "closeAllConnections" to the compareDatasets() function. Otherwise, it does not run on my side.

I appreciate your help!

**Comment by quantixed** [comment] 2023-04-05 15:09
Hi @rosy-li thanks for reporting this issue. Please can you let me know:

- which OS you are using? 
- have you added `closeAllConnections` and know that this solves the problem?
- and finally, are your TrackMate XML files in the suggested directories? It's possible that this may happen because the files cannot be found. They should be in `Data/condition1/`, `Data/condition2/` etc. as described [here](https://quantixed.github.io/TrackMateR/articles/comparison.html)

**Comment by quantixed** [comment] 2023-04-05 15:33
Thank you for your answers. I previously added `closeAllConnections` (somewhere, likely not in the correct place) and it broke something else, so I removed it. I can't reproduce this problem on macOS but I will try to fix when I can access a Windows box (probably next week).

**Comment by rosy-li** [comment] 2023-04-05 15:34
Great, thanks so much!!

**Comment by quantixed** [comment] 2023-04-11 20:35
Hi @HenrikBengtsson thank you so much for diving in to help! After moaning on Mastodon, I had got as far as figuring out some of what you wrote, but the remainder and your explanation overall has cleared up my understanding.

Right now, this part of the code is not working as intended (as you describe). It is a kludge to:

- get R-CMD-check to work
- do parallel processing on Mac
- not do parallel processing on Windows (i.e. issue #11 is intentional) to prevent an error

weirdly it does work and the data gets read but I am not convinced the parallelisation is working properly, because now I have registered the cluster properly on both platforms, I am getting an error with `foreach() %dopar%`. I feel that I am close to getting it working properly though. Thank you!

**Comment by HenrikBengtsson** [comment] 2023-04-11 23:15
> now I have registered the cluster properly on both platforms, I am getting an error with `foreach() %dopar%`

[...] on MS Windows, I assume.

I think this is where I should suggest that you switch to using Futureverse instead, e.g. switch to **doFuture** and `foreach(...) %dofuture% { ... }`. See <https://dofuture.futureverse.org/#alternative-2-dofuture>.  It's designed to make your and user's life much easier, more robust, and more powerful.

**Comment by quantixed** [comment] 2023-04-12 08:17
>[...] on MS Windows, I assume.

Yes, `foreach(...) %do% {...}` works but `foreach(...) %dopar% {...}` doesn't. Mac is working fine. Windows gives:

```
Error in unserialize(socklist[[n]]) : error reading from connection
Error in serialize(data, node$con) : error writing to connection
```

I tried `%dofuture%` it also exits with an error which is at least more verbose (thank you @HenrikBengtsson !)

```
Error in unserialize(node$con) :
MultisessionFuture (doFuture2-1) failed to receive results from cluster RichSOCKnode #1 (PID 20064 on localhost ‘localhost’). The reason reported was ‘error reading from connection’. Post-mortem diagnostic: No process exists with this PID, i.e. the localhost worker is no longer alive. Detected a non-exportable reference (‘externalptr’ of class ‘XMLInternalElementNode’) in one of the globals (‘subdoc’ of class ‘XMLNodeSet’) used in the future expression. The total size of the 3 globals exported is 10.28 MiB. There are three globals: ‘subdoc’ (10.28 MiB of class ‘list’), ‘attrName’ (1.79 KiB of class ‘character’) and ‘...future.x_ii’ (168 bytes of class ‘list’)
```

I don't see how the non-exportable reference could cause the connection(s) to die because it all runs fine on Mac.

**Comment by quantixed** [comment] 2023-04-12 09:36
Closing because the open connections problem is fixed. The problem of parallelisation on Windows is now issue #11

**Closed by quantixed** 2023-04-12 09:36 UTC
Labels: bug

**Comment by rosy-li** [comment] 2023-04-12 16:55
Great. Thanks so much for your help!!!

Best,
Rosy

From: Stephen Royle ***@***.***>
Date: Wednesday, April 12, 2023 at 5:38 AM
To: quantixed/TrackMateR ***@***.***>
Cc: rosy-li ***@***.***>, Mention ***@***.***>
Subject: Re: [quantixed/TrackMateR] Cannot Open the Connections (Issue #9)

@rosy-li<https://github.com/rosy-li> this issue is now fixed. If you update the package using devtools::install_github("quantixed/TrackMateR") it should now work as expected.

**Comment by rosy-li** [comment] 2023-04-12 21:14
Thanks so much! I tried the updated code and it works very well on my computer!
